Algoritmo "OperadoresAritméticos"
Var
nota_matematica,nota_pt,nota_socio,nota_hist,resultado: real
inicio
escreva("Digite sua nota de matemática:")
leia(nota_matematica)
escreva("Digite sua nota de português:")
leia(nota_pt)
escreva("Digite sua nota de sociologia:")
leia(nota_socio)
escreva("Digite sua nota de história:")
leia(nota_hist)
resultado <-(nota_matematica + nota_pt + nota_socio + nota_hist) / 4)

escreva("Sua média é ",resultado)


Fimalgoritmo